import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/components/Providers/ReactQueryProvider";
import { Toaster } from "react-hot-toast";
import Loader from "@/components/Providers/Loader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" bg-zinc-950 overflow-x-hidden">
        <Toaster position="top-center" />
        <ReactQueryProvider>
          <Loader>{children}</Loader>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
